Preparation for release
Esri/pyprt-examples pull request #15
Opened 2021-04-23 06:27 UTC by clechot

2021-04-23 07:10 UTC, clechot commented
Needs to be merged after PR #14

2021-04-23 12:49 UTC, mistafunk reviewed
Example 7 did not work for me on Windows, the paths in cell 3 are wrong. getcwd seems to depend where jupyter is started. So if we use venv activate the cwd of jupyter is inside the venv and it does not find the data folder anymore.

I created a new internal ticket to figure out how to properly read data files inside a jupyter workbook.

Also, I see some low prio issues on Linux:
* Chrome freezes for example 7 before I can click on anything... Firefox works though
* PyGEL3D is still not correctly packaged for Linux: the wheel suffix says "any" but then contains Windows dll and won't load on Linux. Can you maybe do a quick research if there is an alternative to PyGEL3D?

2021-04-26 07:47 UTC, clechot commented
> Example 7 did not work for me on Windows, the paths in cell 3 are wrong. getcwd seems to depend where jupyter is started. So if we use venv activate the cwd of jupyter is inside the venv and it does not find the data folder anymore.

I don't think so. You should be in the examples root directory. On my machine, if I activate the environment from the root directory and then run `jupyter notebook`, I stay in the same folder.

2021-04-28 07:16 UTC, mistafunk requested changes
the commit message "updated package version to latest" is misleading - the version is not the fix but the change to hmesh and jupyter_display does the trick. please cleanup the commit history.

2021-04-28 07:16 UTC, mistafunk commented on envs/py36/requirements.txt
> +PyGEL3D==0.1.4
This reverts commit 921ce717, i.e. we can remove toggling the version from the PR history.

2021-04-28 07:16 UTC, mistafunk commented on ex7_building_modeling_optimization.ipynb
> +    "from pygel3d import hmesh, jupyter_display"
This fixes PyGEL3D on Linux, nice!

The display has the wrong up axis, but at least we can see the model ;-)
![image](https://user-images.githubusercontent.com/1630632/116362018-e546fb00-a801-11eb-967f-1aba9e0fbe0f.png)

2021-04-28 13:54 UTC, mistafunk commented
Cleaned up git history.

2021-04-28 13:54 UTC, merged